title: 장단콩 보드게임 & 미니어처 게임 클럽
description: 장단콩 보드게임 & 미니어처 게임 클럽

url: https://konsent.github.io/jdk/contact/
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag] 
paginate: 5

# [jekyll-paginate]

navigation:
    # - title: 소개
    #   url: /index.html /about /contact
    - title: 회칙
      url: /rules 
    - title: 명예의 전당
      url: /honor
    - title: 콩툰
      url: /toon
    # - title: 공식 이벤트
    #   url: /event


# social:
#     github: brianmaierjr
#     twitter: brianmaierjr
#     facebook: brianmaierjr
#     email: brimaidesigns@gmail.com
#     linkedin: brianmaierjr
#     youtube: RickAstleyYT
#     tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
